### ISSUE TITLE
Tapable.plugin is deprecated.

### ISSUE THREAD

**Issue by Sjoerrdd** [tailwindcss/webpack-starter#11]
I get the following error while running `npm run watch`:

```
Gebruiker@DESKTOP-PA5RD2S MINGW64 ~/desktop/poll (master)
$ npm run watch

> adonis-fullstack-app@4.1.0 watch C:\Users\Gebruiker\desktop\poll
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=webpack.config.js

  0% compiling
Webpack is watching the files…

(node:18800) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead                                                                 77% module and chunk tree optimization unnamed compat pluginC:\Users\Gebruiker\desktop\poll\node_modules\webpack\lib\Chunk.js:460
                throw new Error(
                ^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (C:\Users\Gebruiker\desktop\poll\node_modules\webpack\lib\Chunk.js:460:9)
    at C:\Users\Gebruiker\desktop\poll\node_modules\extract-text-webpack-plugin\dist\index.js:176:48
    at Array.forEach (<anonymous>)
    at C:\Users\Gebruiker\desktop\poll\node_modules\extract-text-webpack-plugin\dist\index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Gebruiker\desktop\poll\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\Gebruiker\desktop\poll\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\Users\Gebruiker\desktop\poll\node_modules\webpack\lib\Compilation.js:881:27)
    at hooks.make.callAsync.err (C:\Users\Gebruiker\desktop\poll\node_modules\webpack\lib\Compiler.js:480:17)
    at _err0 (eval at create (C:\Users\Gebruiker\desktop\poll\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (C:\Users\Gebruiker\desktop\poll\node_modules\webpack\lib\Compilation.js:749:12)
    at processModuleDependencies.err (C:\Users\Gebruiker\desktop\poll\node_modules\webpack\lib\Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adonis-fullstack-app@4.1.0 watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-fullstack-app@4.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gebruiker\AppData\Roaming\npm-cache\_logs\2018-03-21T12_36_06_781Z-debug.log
```

**Comment by Sjoerrdd** [comment]
Clean install solved the problem! :lock:
