### ISSUE TITLE
ERROR in ./src/styles.css

### ISSUE THREAD

**Issue by LukeSeers** [tailwindcss/webpack-starter#31]
I've been trying to figure this out for the past couple of hours... I could be dumb I dont know but I would be greatful if somone can point me in the right direction.

after installing everything I run `npm run dev` then this happens (when I used tailwindccs before I never had this issuse before)

ERROR in ./src/styles.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Error: Cannot find module 'tailwindcss/plugins/container'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\EYT57\Desktop\tailwindcss\tailwind.js:902:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at runLoaders (C:\Users\EYT57\Desktop\tailwindcss\node_modules\webpack\lib\NormalModule.js:301:20)
    at C:\Users\EYT57\Desktop\tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\EYT57\Desktop\tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\EYT57\Desktop\tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (C:\Users\EYT57\Desktop\tailwindcss\node_modules\postcss-loader\lib\index.js:194:71)

ERROR in ./src/styles.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Error: Cannot find module 'tailwindcss/plugins/container'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\EYT57\Desktop\tailwindcss\tailwind.js:902:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at runLoaders (C:\Users\EYT57\Desktop\tailwindcss\node_modules\webpack\lib\NormalModule.js:301:20)
    at C:\Users\EYT57\Desktop\tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\EYT57\Desktop\tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\EYT57\Desktop\tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (C:\Users\EYT57\Desktop\tailwindcss\node_modules\postcss-loader\lib\index.js:194:71)
 @ ./src/styles.css
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!node_modules/postcss-loader/lib/index.js!src/styles.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js?!./node_modules/postcss-loader/lib/index.js!./src/styles.css] ./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/lib!./src/styles.css 839 bytes {1} [built] [failed] [1 error]

    ERROR in ./src/styles.css (./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/lib!./src/styles.css)
    Module build failed (from ./node_modules/postcss-loader/lib/index.js):
    Error: Cannot find module 'tailwindcss/plugins/container'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (C:\Users\EYT57\Desktop\tailwindcss\tailwind.js:902:5)
        at Module._compile (internal/modules/cjs/loader.js:701:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        at Module.load (internal/modules/cjs/loader.js:600:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!node_modules/postcss-loader/lib/index.js!src/styles.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js?!./node_modules/postcss-loader/lib/index.js!./src/styles.css] ./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/lib!./src/styles.css 839 bytes {0} [built] [failed] [1 error]

    ERROR in ./src/styles.css (./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/lib!./src/styles.css)
    Module build failed (from ./node_modules/postcss-loader/lib/index.js):
    Error: Cannot find module 'tailwindcss/plugins/container'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (C:\Users\EYT57\Desktop\tailwindcss\tailwind.js:902:5)
        at Module._compile (internal/modules/cjs/loader.js:701:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        at Module.load (internal/modules/cjs/loader.js:600:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by adamwathan** [comment]
Looks like the problem is that you are trying to use Tailwind 1.0 with a Tailwind 0.7.4 config file maybe? This starter hasn't been updated for 1.0 yet and will be deprecated soon because I don't think it's actually useful for building anything real so we're going to encourage people to use the simpler playground repo instead:

https://github.com/tailwindcss/playground

**Comment by LukeSeers** [comment]
As I figured out what was going on, I thought I would post about it but then I seen you already beat me to it 👍! I recommend not removing `webpack-starter` since there are a few youtube video tutorials pointing people to this repo, so I think it would be a better idea to archive it then in the `ReadMe` point everybody to the `playground` repo instead alot of people would be greatful for that.

**Comment by DeluxZ** [comment]
I can confirm it's because the config is wrong. Once you replace it with [this config](https://raw.githubusercontent.com/tailwindcss/tailwindcss/master/stubs/defaultConfig.stub.js). It should work :)
